/* Personalized daily care, layered over the existing Habita pilot. */
const CARE_GOALS={
 sleep:{name:'Dormir mejor',actions:['sleep','rest','prepare'],dims:['Descanso','Organización'],why:'Preparar una rutina tranquila y regular. Una rutina breve no equivale a tratar el insomnio.',source:'sleep'},
 health:{name:'Cuidar mi salud',actions:['walk','exercise','food'],dims:['Movimiento','Autocuidado'],why:'Encontrar movimiento que se adapte a tus posibilidades. Los minutos del piloto son un punto de partida, no una dosis terapéutica.',source:'health'},
 mental:{name:'Bienestar mental',actions:['walk','social','hobby','rest'],dims:['Conexión','Recreación','Descanso'],why:'Dar espacio a movimiento, conexión y actividades que disfrutas. No sustituye atención psicológica.',source:'mental'},
 focus:{name:'Concentrarme mejor',actions:['goal','rest','prepare'],dims:['Desarrollo personal','Organización'],why:'Elegir una tarea concreta y alternarla con pausas. La evidencia sobre pausas proviene de tareas experimentales específicas.',source:'focus'},
 esteem:{name:'Cuidar mi autoestima',actions:['self','hobby','idea'],dims:['Autonomía','Recreación'],why:'Observar un esfuerzo concreto sin juzgarte. La autocompasión está relacionada con el bienestar, pero este ejercicio no ha sido validado como tratamiento de autoestima.',source:'esteem'}
};
const CARE_SOURCES={
 sleep:{title:'Edinger et al. (2021) · Guía de la AASM para el insomnio crónico',url:'https://doi.org/10.5664/jcsm.8986',text:'Recomienda la terapia cognitivo-conductual para insomnio. No recomienda higiene del sueño como tratamiento único. Habita solo ofrece apoyo a rutinas; no implementa esa terapia.'},
 health:{title:'OMS (2020) · Directrices sobre actividad física y comportamiento sedentario',url:'https://www.who.int/publications/i/item/9789240015128',text:'Respalda actividad física regular adaptada a las posibilidades. Una actividad de pocos minutos puede ser un inicio; no reemplaza las recomendaciones completas. Esta fuente respalda movimiento, no todas las propuestas de alimentación.'},
 mental:{title:'Noetel et al. (2024) · Exercise for depression, BMJ',url:'https://doi.org/10.1136/bmj-2023-075847',text:'Revisión sistemática y metaanálisis de ensayos sobre ejercicio para depresión. No demuestra que Habita trate depresión ni que un paseo breve reproduzca los programas estudiados. Las opciones sociales y recreativas del piloto son propuestas de producto, no intervenciones verificadas por este estudio.'},
 focus:{title:'Ariga y Lleras (2011) · Brief and rare mental breaks',url:'https://doi.org/10.1016/j.cognition.2010.12.007',text:'Experimento sobre atención sostenida: breves interrupciones ayudaron en la tarea estudiada. No establece una duración universal ni valida un temporizador específico.'},
 esteem:{title:'Ferrari et al. (2019) · Self-compassion interventions and psychosocial outcomes',url:'https://doi.org/10.1007/s12671-019-01134-6',text:'Metaanálisis de ensayos de intervenciones de autocompasión. Los programas evaluados son más amplios que reconocer un logro. El ejercicio de Habita es una adaptación de diseño, no una intervención equivalente.'}
};
function careDefaults(){return{configured:false,goals:['sleep'],slots:[{name:'Mañana',time:'09:00',enabled:true},{name:'Tarde',time:'16:00',enabled:true},{name:'Noche',time:'21:00',enabled:true}],room:{kind:'bedroom',wall:'#d8d8c4',floor:'#deceb2'}}}
function validateCare(c){const d=careDefaults();if(c===undefined)return d;if(!c||typeof c!=='object'||Array.isArray(c))throw Error('Plan no compatible');if(!Array.isArray(c.goals)||!c.goals.length||c.goals.length>3||c.goals.some(g=>!Object.hasOwn(CARE_GOALS,g)))throw Error('Objetivos no compatibles');d.goals=[...new Set(c.goals)];d.configured=c.configured===true;if(!Array.isArray(c.slots)||c.slots.length!==3)throw Error('Horarios no compatibles');d.slots=c.slots.map((x,i)=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(x.time))throw Error('Horario no compatible');return{name:d.slots[i].name,time:x.time,enabled:x.enabled===true}});if(c.room){if(!['bedroom','studio'].includes(c.room.kind))throw Error('Espacio no compatible');for(const k of ['wall','floor'])if(!/^#[0-9a-f]{6}$/i.test(c.room[k]))throw Error('Color no compatible');d.room={kind:c.room.kind,wall:c.room.wall,floor:c.room.floor}}return d}
function openCareSetup(first=false){const c=state.profile.care||careDefaults();modal(`<div class="eyebrow">TU PLAN PERSONAL</div><h2 style="margin-top:8px">¿Qué quieres cuidar?</h2><p>Elige hasta tres objetivos. Tú eliges las actividades y puedes cambiar el plan cuando quieras.</p><div class="chips" id="careGoals">${Object.entries(CARE_GOALS).map(([id,g])=>`<button data-goal="${id}" class="${c.goals.includes(id)?'on':''}" onclick="this.classList.toggle('on')">${g.name}</button>`).join('')}</div><label for="careMinutes">Tiempo para un pequeño paso</label><select id="careMinutes">${[3,5,10,15,20].map(n=>`<option ${state.profile.minutes===n?'selected':''}>${n}</option>`).join('')}</select><label for="careEnergy">Energía que tienes hoy</label><select id="careEnergy">${[1,2,3,4,5].map(n=>`<option value="${n}" ${state.profile.energy===n?'selected':''}>${['Muy poca','Poca','Intermedia','Bastante','Mucha'][n-1]}</option>`).join('')}</select><label class="check"><input id="careAvoid" type="checkbox" ${state.profile.avoidPhysical?'checked':''}>Prefiero propuestas sin ejercicio físico</label><label class="check"><input id="careIndoors" type="checkbox" ${state.profile.indoors?'checked':''}>Prefiero actividades en casa</label><h3 style="margin-top:20px">Tus momentos del día</h3><p class="small">Avisos dentro de Habita mientras está abierta. Si vuelves más tarde, verás el último pendiente. No llegan con la app cerrada. Hora local de tu dispositivo.</p>${c.slots.map((x,i)=>`<div class="row"><label class="check grow"><input type="checkbox" id="slotOn${i}" ${x.enabled?'checked':''}>${x.name}</label><input aria-label="Hora ${x.name}" id="slotTime${i}" type="time" value="${x.time}" style="width:125px"></div>`).join('')}<button class="btn full" style="margin-top:20px" onclick="saveCareSetup()">${first?'Comenzar mi plan':'Guardar mi plan'}</button><button class="textbtn full" onclick="openEvidence()">Conocer la base científica</button>`)}
function saveCareSetup(){const goals=[...$('#careGoals').querySelectorAll('.on')].map(x=>x.dataset.goal);if(!goals.length||goals.length>3)return toast('Elige entre uno y tres objetivos.');const old=state.profile.care||careDefaults();let candidate={...old,configured:true,goals,slots:old.slots.map((x,i)=>({...x,time:$('#slotTime'+i).value,enabled:$('#slotOn'+i).checked}))};try{candidate=validateCare(candidate)}catch{return toast('Revisa las horas de tus recordatorios.')}state.profile.care=candidate;state.profile.minutes=Number($('#careMinutes').value);state.profile.energy=Number($('#careEnergy').value);state.profile.avoidPhysical=$('#careAvoid').checked;state.profile.indoors=$('#careIndoors').checked;state.profile.goals=[...new Set(goals.flatMap(g=>CARE_GOALS[g].dims))];state.onboard=true;current=null;save();closeModal();navigate('world');checkCareReminder();toast('Tu plan está listo. Puedes adaptarlo cada día.')}
function careSuggestion(){const c=state.profile.care||careDefaults(),hour=new Date().getHours(),base=suggest(state,run(),'home',hour);let ids=[...new Set(c.goals.flatMap(g=>CARE_GOALS[g].actions))];ids=ids.filter(id=>!(ACTIONS[id].physical&&state.profile.avoidPhysical)&&!(state.profile.indoors&&['walk','box'].includes(id)));if(hour>=19&&c.goals.includes('sleep'))ids=['sleep',...ids.filter(x=>x!=='sleep')];const done=run().records.filter(r=>r.day===day()&&r.status==='done').map(r=>r.action);if(hour<19||!c.goals.includes('sleep'))ids.sort((a,b)=>Number(done.includes(a))-Number(done.includes(b)));ids=ids.filter(id=>run().barriers[id]?.reason!=='opportunity'&&run().barriers[id]?.reason!=='interest');if(!ids.length)ids=['rest','self','prepare'];const options=ids.slice(0,3).map(id=>{const a=ACTIONS[id],barrier=run().barriers[id],small=state.profile.energy<=2||['time','energy','capacity'].includes(barrier?.reason);return{id,duration:small?a.min:Math.max(a.min,Math.min(a.minutes,state.profile.minutes)),adapted:small?'Un paso más pequeño para hoy.':'',next:null}});return{...base,id:'care',title:'Un pequeño paso para ti.',text:c.goals.map(g=>CARE_GOALS[g].name).join(' · '),options}}
function openEvidence(action=null){const c=state.profile.care||careDefaults();const goals=action?Object.keys(CARE_GOALS).filter(g=>CARE_GOALS[g].actions.includes(action)):c.goals;modal(`<div class="eyebrow">CIENCIA Y TRANSPARENCIA</div><h2 style="margin-top:8px">Por qué lo proponemos.</h2><p>Las fuentes orientan las propuestas. Habita no ha sido evaluada en un ensayo clínico y no garantiza mejoras. Los efectos dependen de la persona, la constancia y el contexto.</p>${goals.map(id=>{const g=CARE_GOALS[id],s=CARE_SOURCES[g.source];return `<details open><summary>${g.name}</summary><p>${g.why}</p><a href="${s.url}" target="_blank" rel="noopener">${s.title}</a><p class="small">${s.text}</p></details>`}).join('')}<p class="small">Las duraciones, el orden de las actividades y las recompensas de Habita son decisiones de diseño; estas fuentes no validan ese sistema. Si el sueño o el malestar afectan tu vida de forma persistente, busca apoyo profesional.</p><button class="btn full" onclick="closeModal()">Volver</button>`)}
function dueCareSlot(now=new Date()){const slots=state.profile.care?.slots||[],minutes=now.getHours()*60+now.getMinutes();return slots.map((x,i)=>({...x,index:i,minute:Number(x.time.slice(0,2))*60+Number(x.time.slice(3))})).filter(x=>x.enabled&&x.minute<=minutes).sort((a,b)=>b.minute-a.minute)[0]||null}
function checkCareReminder(){if(mode!=='real'||!state.profile.care?.configured||document.hidden)return;const slot=dueCareSlot();if(!slot)return;const key=new Date().toLocaleDateString('en-CA')+'-'+slot.index;const d=run();d.reminders=d.reminders||{};if(d.reminders[key])return;d.reminders[key]=true;const keys=Object.keys(d.reminders);while(keys.length>30)delete d.reminders[keys.shift()];save();toast('Tu momento de '+slot.name.toLowerCase()+': ¿te viene bien un pequeño paso?');if(page==='world')syncHome()}
function openRoom(){const r=state.profile.care?.room||careDefaults().room;modal(`<div class="eyebrow">TU CASA EN HABITA</div><h2 style="margin-top:8px">Un rincón que se parezca al tuyo.</h2><p>Toma una foto de referencia y elige cómo es tu espacio. La foto queda en este navegador. Esta versión no escanea dimensiones ni reconstruye una habitación automáticamente.</p>${state.profile.photo?`<img src="${state.profile.photo}" alt="Referencia de tu habitación" style="width:100%;max-height:150px;object-fit:cover;border-radius:14px">`:''}<button class="btn secondary full" onclick="$('#photoFile').click()">${state.profile.photo?'Cambiar foto de referencia':'Tomar o elegir una foto'}</button><label for="roomKind">Mi rincón</label><select id="roomKind"><option value="bedroom" ${r.kind==='bedroom'?'selected':''}>Dormitorio</option><option value="studio" ${r.kind==='studio'?'selected':''}>Estudio</option></select><div class="grid2"><div><label for="roomWall">Paredes</label><input id="roomWall" type="color" value="${r.wall}"></div><div><label for="roomFloor">Suelo</label><input id="roomFloor" type="color" value="${r.floor}"></div></div><button class="btn full" style="margin-top:20px" onclick="saveRoom()">Guardar mi espacio</button>`)}
function saveRoom(){state.profile.care=state.profile.care||careDefaults();state.profile.care.room={kind:$('#roomKind').value,wall:$('#roomWall').value,floor:$('#roomFloor').value};save();closeModal();navigate('world');toast('Tu rincón cambió contigo.')}

function careInstructions(id){return {sleep:'Prepara un cierre tranquilo del día: deja listo lo de mañana y elige una actividad relajante antes de acostarte. Mantén horarios de sueño que puedas sostener.',goal:'Elige una sola tarea pequeña. Aparta las distracciones que puedas y dedícale este rato; al terminar, haz una pausa.',self:'Escribe un esfuerzo concreto que hiciste hoy. Respóndete como le responderías a alguien que aprecias, sin exigir que todo haya salido bien.',rest:'Busca una postura cómoda y deja un momento sin tareas. Puedes mirar por la ventana o escuchar tu entorno.',exercise:'Elige movimientos suaves que ya conozcas y sean cómodos para ti. Adapta el esfuerzo a tus posibilidades.',walk:'Camina por un lugar seguro a un ritmo cómodo. Puedes elegir una versión breve y volver cuando quieras.'}[id]||ACTIONS[id].gain+'. Elige una versión concreta que quepa en tu día.'}
