/* Opt-in original audio, durable activity timer and procedural local companion. */
const QuietSound={on:false,ctx:null,loop:null,step:0,
 async toggle(){try{if(this.on){this.on=false;clearInterval(this.loop);await this.ctx?.suspend()}else{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return toast('Este navegador no permite activar el sonido.');this.ctx=this.ctx||new AC();await this.ctx.resume();this.on=true;this.melody();this.loop=setInterval(()=>this.melody(),12000)}this.label()}catch{this.on=false;this.label();toast('No pudimos activar el sonido. Puedes seguir sin audio.')}},
 label(){const b=$('#soundControl');b.setAttribute('aria-pressed',String(this.on));b.setAttribute('aria-label',this.on?'Silenciar música y alertas':'Activar música y alertas suaves');b.textContent=this.on?'♫':'♪';b.classList.toggle('enabled',this.on)},
 note(freq,when,duration=2,volume=.025){if(!this.on||!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime+when,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.16);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration+.05);o.onended=()=>{o.disconnect();g.disconnect()}},
 melody(){if(document.hidden)return;const sequence=[261.63,329.63,392,329.63,293.66,349.23,440,392];for(let i=0;i<4;i++)this.note(sequence[(this.step+i)%sequence.length],i*2.8,3.8,.018);this.note(130.81,0,10,.013);this.step=(this.step+4)%sequence.length},
 chime(){if(this.on&&this.ctx?.state==='suspended'){this.ctx.resume().then(()=>{if(this.on)this.chime()}).catch(()=>{});return}this.note(523.25,0,1.8,.025);this.note(659.25,.3,2,.021);this.note(783.99,.65,2.2,.017)}
};
let pendingCareNotice=null,rewardTimeout=null;
function reminderKey(slot){return new Date().toLocaleDateString('en-CA')+'-'+slot.index}
function showActivityNotice(slot){if(run().active)return;pendingCareNotice={slot,key:reminderKey(slot)};renderActivityNotice();QuietSound.chime();}
function renderActivityNotice(){const el=$('#activityNotice');if(!el)return;const show=!!pendingCareNotice&&mode==='real'&&!run().active&&page==='world';el.classList.toggle('hidden',!show);if(show){$('#noticeTitle').textContent='Tu momento de '+pendingCareNotice.slot.name.toLowerCase();$('#noticeActivity').textContent=ACTIONS[careSuggestion().options[0].id].name}}
function openActivityNotice(){const o=careSuggestion().options[0],a=ACTIONS[o.id];modal(`<div class="eyebrow">TU MOMENTO · ${pendingCareNotice?esc(pendingCareNotice.slot.time):'A TU RITMO'}</div><h2 style="margin-top:8px">${a.name}</h2><p>${esc(careInstructions(o.id))}</p><div class="notice">${o.duration} minutos · ${esc(a.dim)}<br><span class="small">Puedes terminar antes o dejarlo para otro momento.</span></div><button class="btn full" onclick="beginSuggestedActivity('${o.id}',${o.duration})">Empezar · ${o.duration} min</button><button class="textbtn full" onclick="dismissActivityNotice();closeModal()">Ahora no</button><button class="textbtn full" onclick="dismissActivityNotice();openDecision('home')">Elegir otra actividad</button>`)}
function dismissActivityNotice(){if(pendingCareNotice){const d=run();d.reminderAcks=d.reminderAcks||{};d.reminderAcks[pendingCareNotice.key]=true;const keys=Object.keys(d.reminderAcks);while(keys.length>30)delete d.reminderAcks[keys.shift()];save()}pendingCareNotice=null;renderActivityNotice()}
function beginSuggestedActivity(id,duration){if(run().active)return;current=careSuggestion();const o=current.options.find(x=>x.id===id);if(!o)return;run().active={id:uid(),action:id,duration:o.duration,situation:current.id,title:current.title,day:day(),date:stamp()};run().choices.push({action:id,situation:current.id,status:'accepted',day:day()});dismissActivityNotice();startCareTimer();}
function startCareTimer(){const c=run().active;if(!c)return;if(!c.timerEnd)c.timerEnd=Date.now()+c.duration*60000;save();closeModal();navigate('world');timerTick();}
function timerTick(){const c=run().active,el=$('#careTimer');if(!el)return;if(!c?.timerEnd){el.classList.add('hidden');return}el.classList.remove('hidden');const remaining=Math.max(0,Math.ceil((c.timerEnd-Date.now())/1000));$('#careTimerValue').textContent=Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');$('#careTimerLabel').textContent=remaining?'Tu pequeño momento':'Tu tiempo terminó · vuelve a tu ritmo';$('#careTimerProgress').style.setProperty('--progress',String(1-Math.min(1,remaining/(c.duration*60))));if(!remaining&&!c.timerAlerted&&!document.hidden){c.timerAlerted=true;save();QuietSound.chime();toast('Tu tiempo terminó. Cuando quieras, toca «Ya lo hice».')}renderActivityNotice()}
function companionHome(){const c=run().active;$('#homeCard').classList.toggle('isActive',!!c);if(c){$('#homeMode').textContent=mode==='demo'?'ACTIVIDAD DE ENSAYO':'TU ACTIVIDAD';$('#homeCard h2').textContent=ACTIONS[c.action].name;$('#phaseNote').textContent=careInstructions(c.action);$('#homeCopy').textContent='Tú decides cuándo darla por realizada.';$('#homeSchedule').textContent='';$('#homeAction').textContent='Ya lo hice';$('#homeAction').onclick=finishAction;$('#activityControls').classList.remove('hidden');$('#timerStart').classList.toggle('hidden',!!c.timerEnd);$('#homePlanLink').classList.add('hidden')}else{$('#homeCard h2').textContent='Un momento para cuidarte.';$('#homeAction').textContent='Ver mi actividad';$('#homeAction').onclick=openActivityNotice;$('#phaseNote').textContent=realClock().phase.message;$('#activityControls').classList.add('hidden');$('#homePlanLink').classList.remove('hidden')}timerTick();renderActivityNotice()}
function showCareReward(action){const d=run(),dim=ACTIONS[action].dim,n=d.records.filter(r=>r.status==='done'&&r.day===day()).length;$('#rewardDimension').textContent=dim+' · +1 registro';$('#rewardCount').textContent=n+' '+(n===1?'paso registrado':'pasos registrados')+' hoy';$('#careReward').classList.remove('hidden');$('#careReward').setAttribute('aria-label','Paso registrado. '+dim+'. '+n+' registros hoy. Son registros de actividad, no mediciones de salud.');clearTimeout(rewardTimeout);rewardTimeout=setTimeout(()=>$('#careReward').classList.add('hidden'),6500);QuietSound.chime();}
function preferenceScore(action){const d=run(),records=d.records.filter(r=>r.action===action),done=records.filter(r=>r.status==='done').length,skip=records.filter(r=>r.status==='deferred').length;return(done+1)/(done+skip+2)}
const COMPANION_TASKS=[
 {id:'read',label:'leer unas páginas',anim:'read',at:[3.5,5.5],actions:['learn','idea','goal'],prop:'book'},
 {id:'write',label:'anotar una idea',anim:'write',at:[3.5,3.5],actions:['idea','goal','self','prepare'],prop:'pencil'},
 {id:'water',label:'cuidar su planta',anim:'water',at:[5.5,5.5],actions:['organize','water','food'],prop:'water'},
 {id:'tea',label:'preparar una taza',anim:'eat',at:[3.5,5.5],actions:['food','water','rest','social'],prop:'cup'},
 {id:'rest',label:'hacer una pausa junto a su gato',anim:'sit',at:[4.5,4.5],actions:['rest','sleep','self'],prop:'heart'},
 {id:'window',label:'contemplar la luz de la ventana',anim:'look',at:[4.5,3.5],actions:['walk','rest','hobby'],prop:'spark'},
 {id:'stretch',label:'estirarse despacio',anim:'stretch',at:[4.5,5.5],actions:['exercise','walk','box'],prop:null},
 {id:'tidy',label:'acomodar su rincón',anim:'tidy',at:[3.5,3.5],actions:['organize','prepare','goal'],prop:'cloth'},
 {id:'draw',label:'dibujar algo que le gusta',anim:'draw',at:[3.5,5.5],actions:['hobby','idea','self'],prop:'pencil'},
 {id:'cat',label:'acariciar a su gato',anim:'pet',at:[4.5,5.5],actions:['social','self','hobby'],prop:'heart'}
];
const Companion={task:null,remaining:0,phase:'idle',queue:[],idle:12,serial:0,history:[],lastAction:null,
 reset(){this.task=null;this.queue=[];this.phase='idle';this.idle=12;this.lastAction=null;const el=$('#companionStatus');if(el)el.classList.add('hidden')},
 choose(action=null){let choices=COMPANION_TASKS.filter(t=>!this.history.slice(-2).includes(t.id)&&!(state.profile.avoidPhysical&&t.id==='stretch'));const h=realClock().hour,weights=choices.map(t=>{let w=1;if(action&&t.actions.includes(action))w+=5;const interests=(state.profile.care?.goals||[]).flatMap(g=>CARE_GOALS[g].actions);w+=t.actions.filter(id=>interests.includes(id)).length*.7;w+=t.actions.reduce((n,id)=>n+preferenceScore(id),0)/t.actions.length*2;if(h>=21&&['rest','window','read','cat'].includes(t.id))w+=2;return w});let roll=Math.random()*weights.reduce((a,b)=>a+b,0);let idx=0;for(;idx<weights.length-1;idx++){roll-=weights[idx];if(roll<=0)break}const t=choices[idx];const openings=['Ahora le apetece','Con calma, decide','En su pequeño rincón quiere','Se toma un momento para'];return{...t,duration:12+Math.floor(Math.random()*19),caption:openings[Math.floor(Math.random()*openings.length)]+' '+t.label+'.',serial:++this.serial}},
 begin(action){this.lastAction=action;this.queue=Array.from({length:3},()=>action);this.task=null;this.phase='idle';this.idle=0;this.next()},
 next(){if(!world||world.zone!=='home')return;const t=this.choose(this.queue.length?this.queue.shift():null);this.history.push(t.id);this.history=this.history.slice(-8);this.task=t;this.phase='travel';this.remaining=0;world.keys.clear();if(!world.go(...t.at)){this.task=null;this.idle=5;return}this.status('Camina para '+t.label+'…')},
 status(text){const el=$('#companionStatus');if(!el)return;el.textContent=text;el.classList.toggle('hidden',page!=='world'||world.zone!=='home');},
 update(dt){if(!world||world.zone!=='home'||world.paused||page!=='world')return;if(this.task){if(this.phase==='travel'){if(world.keys.size){this.cancel();return}if(!world.path.length){this.phase='doing';this.remaining=this.task.duration;world.react(this.task.anim,this.task.duration+1);this.status(this.task.caption)}}else{this.remaining-=dt;if(this.remaining<=0){this.task=null;this.phase='idle';this.idle=3+Math.random()*6}}}else{this.idle-=dt;if(this.idle<=0)this.next()}},
 cancel(){this.task=null;this.queue=[];this.idle=18;$('#companionStatus')?.classList.add('hidden')}
};
function openCompanionAbout(){modal(`<div class="eyebrow">TU COMPAÑERO</div><h2 style="margin-top:8px">Un ritmo que se parece al tuyo.</h2><p>Sus decisiones consideran tus actividades realizadas, las que pospones, la hora del día y sus tareas recientes. También introduce variación al azar.</p><p>Combina movimientos, objetos, duraciones y gestos para seguir creando secuencias. El catálogo de tareas es finito y puede ampliarse; no inventa habilidades nuevas ni tiene conciencia.</p><p class="small">Sus gestos y los indicadores son ficción y registros de actividad, no una evaluación de tu salud o personalidad. El aprendizaje se calcula con los datos locales de esta partida; puedes corregir tus registros.</p><button class="btn full" onclick="closeModal()">Volver a mi rincón</button>`)}
function initCompanion(){setInterval(timerTick,500);QuietSound.label();const P=HabitaWorld.prototype,oldUpdate=P.update,oldDraw=P.drawPerson,oldInterior=P.drawInterior;
 P.update=function(dt,now){oldUpdate.call(this,dt,now);Companion.update(dt)};
 thisInputCancel();
 P.drawPerson=function(x,y,anim,npc=false){oldDraw.call(this,x,y,anim,npc);if(npc||this.zone!=='home'||!Companion.task||Companion.phase!=='doing')return;const q=this.project(x,y),c=this.ctx,t=this.time,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,sway=reduced?0:Math.sin(t*2)*3,prop=Companion.task.prop;c.save();c.translate(q.x+14,q.y-28+sway);
 if(prop==='water'){this.round(-4,-2,11,8,2,'#79b9c1','#417681');this.line({x:7,y:0},{x:18,y:5},'#79b9c1',3);for(let i=0;i<3;i++)this.ellipse(18+i*3,8+((t*12+i*4)%10),1,2,'#94cbd1')}
 if(prop==='pencil'){this.round(-13,-2,22,14,2,'#fff1ce','#c3a78d');this.line({x:-2,y:2},{x:4+sway,y:9},'#777aa3',2)}
 if(prop==='cloth')this.round(-4,0,13,7,2,'#e8be83');
 if(prop==='heart'){c.fillStyle='#d59bb0';c.font='15px sans-serif';c.fillText('♡',-6,-8)}
 if(prop==='spark'){c.fillStyle='#ddbd79';c.font='16px sans-serif';c.fillText('·',0,-6)}c.restore();};
 P.drawInterior=function(){oldInterior.call(this);if(this.zone==='home'&&Companion.task?.id==='cat'&&Companion.phase==='doing'){this.cat.x=this.player.x-.6;this.cat.y=this.player.y+.35}};
 document.addEventListener('visibilitychange',()=>{if(QuietSound.on){if(document.hidden)QuietSound.ctx?.suspend();else QuietSound.ctx?.resume().catch(()=>{})}if(!document.hidden)timerTick()});
 Companion.next();timerTick();
}
function thisInputCancel(){world.listen(world.canvas,'pointerdown',()=>Companion.cancel());world.listen(window,'keydown',e=>{if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(e.key.toLowerCase()))Companion.cancel()})}
