
/* Habita 02: transparent, local rule-based adaptation. Conceptual references, not clinical instruments. */
const ACTIONS={
walk:{name:'Dar un paseo',icon:'🚶',dim:'Movimiento',minutes:10,min:3,max:20,anim:'walk',color:'#4a9677',cost:'Salir y cambiar de ambiente',gain:'Dejar espacio para observar',physical:true,place:'beach'},
exercise:{name:'Moverme en casa',icon:'🤸',dim:'Movimiento',minutes:8,min:2,max:15,anim:'stretch',color:'#5f9d88',cost:'Usar un poco de energía',gain:'Moverte sin desplazarte',physical:true,place:'home'},
box:{name:'Practicar boxeo según mi plan',icon:'🥊',dim:'Movimiento',minutes:10,min:3,max:20,anim:'train',color:'#ce8068',cost:'Reservar un momento para practicar',gain:'Continuar algo que disfrutas',physical:true,place:'gym'},
rest:{name:'Tomarme una pausa tranquila',icon:'🌙',dim:'Descanso',minutes:5,min:2,max:15,anim:'sit',color:'#9185b7',cost:'Dejar otra cosa para después',gain:'Darte espacio sin exigencias',place:'park'},
sleep:{name:'Preparar mi descanso',icon:'🛏',dim:'Descanso',minutes:5,min:2,max:10,anim:'sleep',color:'#9185b7',cost:'Cerrar por hoy una actividad',gain:'Preparar tu propia rutina',place:'home'},
learn:{name:'Leer o aprender algo que me interesa',icon:'📖',dim:'Aprendizaje',minutes:10,min:3,max:20,anim:'read',color:'#6a98be',cost:'Elegir una sola curiosidad',gain:'Dar un paso en algo propio',place:'library'},
idea:{name:'Escribir una idea',icon:'💡',dim:'Desarrollo personal',minutes:2,min:1,max:5,anim:'think',color:'#c79e50',cost:'Hacer una pausa para pensar',gain:'Guardar algo que no quieres olvidar',place:'library'},
goal:{name:'Avanzar en un proyecto personal',icon:'🧩',dim:'Desarrollo personal',minutes:15,min:3,max:20,anim:'interact',color:'#c79e50',cost:'Dejar otros pendientes en espera',gain:'Elegir una parte pequeña y concreta',place:'office'},
organize:{name:'Ordenar un pequeño rincón',icon:'🪴',dim:'Entorno',minutes:5,min:2,max:10,anim:'interact',color:'#69a376',cost:'Dedicarle atención a tu espacio',gain:'Hacer más agradable un lugar cotidiano',place:'home'},
prepare:{name:'Preparar algo para mañana',icon:'🎒',dim:'Organización',minutes:5,min:2,max:10,anim:'interact',color:'#6e9e88',cost:'Anticipar una necesidad concreta',gain:'Simplificar un pequeño paso de mañana',place:'office'},
social:{name:'Contactar a alguien que me importa',icon:'🤝',dim:'Conexión',minutes:5,min:2,max:15,anim:'wave',color:'#cb9179',cost:'Abrir un espacio a otra persona',gain:'Compartir algo, sin exigir respuesta',place:'cafe'},
hobby:{name:'Dedicar tiempo a un hobby',icon:'🎨',dim:'Recreación',minutes:10,min:3,max:20,anim:'celebrate',color:'#bc83a4',cost:'Pausar lo productivo por un rato',gain:'Hacer algo por el gusto de hacerlo',place:'park'},
food:{name:'Preparar algo sencillo para comer',icon:'🥗',dim:'Autocuidado',minutes:10,min:5,max:20,anim:'eat',color:'#89a55e',cost:'Usar ingredientes y tiempo disponibles',gain:'Elegir una preparación que disfrutes',place:'home'},
water:{name:'Hacer una pausa para beber agua',icon:'💧',dim:'Autocuidado',minutes:1,min:1,max:2,anim:'eat',color:'#6badd0',cost:'Interrumpir un momento lo que haces',gain:'Atender una necesidad cotidiana',place:'office'},
alcohol:{name:'Preparar una salida acorde a mi decisión',icon:'🍃',dim:'Autonomía',minutes:3,min:1,max:5,anim:'think',color:'#789c87',cost:'Decidir antes de salir',gain:'Elegir no beber o cómo sostener tu decisión personal',place:'cafe'},
self:{name:'Reconocer algo que hice bien',icon:'🌱',dim:'Autonomía',minutes:2,min:1,max:5,anim:'curious',color:'#97ab69',cost:'Parar un momento la autocrítica',gain:'Observar un avance concreto, por pequeño que sea',place:'home'}
};
const DECK=[
{id:'air',title:'Parece que necesita cambiar de aire.',text:'Tu personaje mira por la ventana y luego se estira. Hay varias formas de pasar este rato.',context:['home','beach'],opts:['walk','exercise','rest']},
{id:'hour',title:'Este rato es tuyo.',text:'No todo cabe en el mismo momento. ¿A qué te gustaría darle espacio hoy?',context:['any'],opts:['box','social','learn']},
{id:'desk',title:'El escritorio puede esperar un momento.',text:'Tu personaje aparta la silla. Una pequeña pausa también puede tener distintos destinos.',context:['office'],opts:['exercise','water','idea']},
{id:'shelf',title:'Hay un libro con una nota adentro.',text:'La biblioteca abre una curiosidad. Puedes seguirla ahora o dedicar tu atención a otra cosa.',context:['library'],opts:['learn','idea','hobby']},
{id:'club',title:'La puerta del club está entreabierta.',text:'Desde adentro alguien saluda. ¿Qué te gustaría hacer con tu tiempo?',context:['gym'],opts:['box','social','rest']},
{id:'table',title:'Una mesa vacía frente al mar.',text:'Tu personaje acomoda dos sillas y piensa un momento. No hace falta llenarlas hoy.',context:['cafe','park'],opts:['social','hobby','rest']},
{id:'tomorrow',title:'¿Qué le dejamos preparado a mañana?',text:'El gato inspecciona una mochila abierta. Tu personaje encuentra espacio para una cosa más.',context:['home','office'],opts:['prepare','organize','sleep']},
{id:'shore',title:'La marea dejó una marca extraña.',text:'Tu personaje se agacha a observarla. Quizá caminar, aprender o imaginar lleve a lugares distintos.',context:['beach','trail','bridge'],opts:['walk','learn','hobby']},
{id:'garden',title:'Este rincón podría tener otra vida.',text:'Un vecino dejó una maceta. Aún no hay un plan, solo una posibilidad.',context:['park','home'],opts:['organize','hobby','social']},
{id:'care',title:'Un momento para atenderte.',text:'Tu personaje deja lo que tenía entre manos. ¿Qué te vendría bien ahora?',context:['home','office'],opts:['food','water','rest']},
{id:'own',title:'Hay algo que te gustaría hacer por ti.',text:'Un cuaderno abierto, una canción y una silla al sol. Tú decides qué merece este rato.',context:['any'],opts:['goal','self','hobby']},
{id:'evening',title:'El día empieza a bajar el ritmo.',text:'Tu personaje enciende una pequeña lámpara. Queda tiempo para algo sencillo.',context:['home','cafe'],opts:['sleep','social','alcohol']}
];
function freshRun(){return{day:0,records:[],choices:[],active:null,flags:{trail:false,bridge:false,library:false,garden:false,friend:false,expedition:false},events:[],future:[],memories:[],barriers:{},seen:[],discovered:['plaza'],mood:'curious',energy:3,wellbeing:{},friend:null,reminders:{},reminderAcks:{},companionMemory:{recent:[],total:0}}}
function freshState(){return{version:2,profile:{name:'Alex',cat:'Michi',shirt:'#245c70',skin:'#d69c76',hair:'#322d35',goals:['Movimiento','Descanso','Aprendizaje'],minutes:10,energy:3,indoors:false,avoidPhysical:false,photo:null,avatar:{hairStyle:'short',outfit:'casual',accessory:'none',silhouette:'regular'},interests:[],timeZone:'America/Santiago',care:careDefaults()},real:freshRun(),demo:freshRun(),onboard:false,legacy:null}}
function habitaTime(date=new Date()){let timeZone='America/Santiago';try{timeZone=state.profile.timeZone||timeZone}catch{}const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date);const values=Object.fromEntries(parts.map(p=>[p.type,p.value]));return{hour:Number(values.hour),minute:Number(values.minute),date:values.year+'-'+values.month+'-'+values.day,timeZone};}
const localDate=()=>habitaTime().date;
function counts(run){const c={};run.records.filter(r=>r.status==='done').forEach(r=>c[r.action]=(c[r.action]||0)+1);return c}
function suggest(state,run,context,hour=12){const done=counts(run),recent=run.seen.slice(-4),score=s=>{let n=s.context.includes(context)?6:0;if(s.context.includes('any'))n+=1;if(recent.includes(s.id))n-=10;if(hour>=20&&s.id==='evening')n+=8;if(state.profile.energy<=2&&s.opts.includes('rest'))n+=2;for(const id of s.opts){const a=ACTIONS[id];if(state.profile.goals.includes(a.dim))n+=1;const b=run.barriers[id];if(b?.reason==='interest')n-=2;}if(run.flags.trail&&s.id==='shore')n+=1;if(run.flags.friend&&s.id==='table')n+=1;if(run.energy<=2&&s.opts.includes('rest'))n+=1;return n};const ranked=DECK.map((s,i)=>({s,score:score(s),i})).sort((a,b)=>b.score-a.score||((a.i+run.choices.length)%DECK.length)-((b.i+run.choices.length)%DECK.length));const s=ranked[0].s;let ids=[...s.opts];const alternatives=['rest','idea','social','hobby','prepare'];ids=ids.map(id=>{const a=ACTIONS[id],b=run.barriers[id],recentSkip=run.choices.slice(-5).filter(x=>x.action===id&&x.status==='deferred').length;return (a.physical&&state.profile.avoidPhysical)||(['walk','box'].includes(id)&&state.profile.indoors)||(b?.reason==='opportunity')||((b?.reason==='interest'||recentSkip>=2)&&run.choices.length-(b?.at||0)<6)?alternatives.find(z=>!ids.includes(z))||'self':id});ids=[...new Set(ids)];while(ids.length<3)ids.push(alternatives.find(z=>!ids.includes(z)));const options=ids.map(id=>{const a=ACTIONS[id],b=run.barriers[id];let duration=Math.min(a.minutes,state.profile.minutes);let adapted='';if(state.profile.energy<=2&&a.physical){duration=Math.min(duration,5);adapted='Una versión más breve, según tu energía.'}if(b?.reason==='energy'){duration=a.min;adapted='Una versión pequeña para un día con menos energía.'}if(b?.reason==='time'||b?.reason==='capacity'){duration=a.min;adapted=b.reason==='time'?'Más breve, porque antes faltó tiempo.':'Un primer paso pequeño, según lo que nos contaste.'}duration=Math.max(a.min,duration);const days=new Set(run.records.filter(r=>r.action===id&&r.status==='done').map(r=>r.day));const next=days.size>=3&&!b&&duration<a.max?Math.min(a.max,duration+2):null;return{id,duration,adapted,next}});return{id:s.id,title:s.title,text:s.text,options,context}}
function unlocks(run){const c=counts(run),out=[];const add=(flag,title,text)=>{if(!run.flags[flag]){run.flags[flag]=true;out.push({flag,title,text})}};
if(c.learn||c.idea)add('library','La biblioteca tiene algo para ti','La bibliotecaria dejó una mesa preparada. Puedes entrar y explorar.');
if((c.walk||0)>=2||(c.learn||0)+(c.hobby||0)+(c.rest||0)>=3)add('trail','Se revela el sendero de la costa','Tus pequeñas acciones hicieron aparecer una ruta entre la niebla. Hay más de una forma de llegar hasta aquí.');
if((c.organize||0)+(c.hobby||0)>=2)add('garden','Un rincón florece','El vecino plantó flores junto a la plaza. Tu manera de cuidar o disfrutar el entorno dejó una huella.');
if((c.social||0)>=1&&((c.walk||0)+(c.learn||0)+(c.hobby||0)>=1))add('friend','Alguien te espera en la plaza','Una conversación y una curiosidad se encontraron. Un personaje nuevo quiere compartir una historia.');
if(run.flags.trail&&((c.learn||0)+(c.idea||0)>=2)&&((c.prepare||0)+(c.social||0)+(c.organize||0)>=1))add('bridge','El puente vuelve a unir las orillas','Las ideas y la colaboración encontraron una solución. Ahora puedes cruzar y descubrir qué hay detrás.');
if(run.flags.bridge&&((c.rest||0)+(c.sleep||0)>=2))add('expedition','Una luz al otro lado','Después de varios momentos de recuperación, aparece una invitación para una expedición tranquila.');return out}
const CONSEQUENCES={walk:['Una marca en la arena','Tu personaje pasea, mira el paisaje y descubre una línea dibujada entre las piedras.','Una piedra con un símbolo'],exercise:['La ventana abierta','Después de estirarse, tu personaje abre una ventana. Una hoja dibujada llega con el viento.','Hoja que trajo el viento'],box:['Un saludo desde el club','Tu personaje practica unos movimientos. Alguien acerca un banco y deja una invitación.','Invitación del club'],rest:['Lo que se oye al detenerse','Tu personaje se sienta. Entre las olas distingue una pequeña melodía que antes no había escuchado.','Melodía de la costa'],sleep:['Una mañana sin prisa','Tu personaje se acurruca y sueña con un sendero. Deja su mochila preparada para otra visita.','Boceto de un sueño'],learn:['Un símbolo conocido','Tu personaje lee. Una ilustración se parece a las marcas que aparecen por el barrio.','Página anotada'],idea:['Una idea que encuentra lugar','Tu personaje piensa y dibuja unas líneas. El boceto podría servir para conectar dos orillas.','Boceto del puente'],goal:['Una pieza más','Tu personaje revisa su pequeño proyecto. Una parte que parecía suelta por fin encuentra sitio.','Pieza de un proyecto'],organize:['La caja olvidada','Mientras acomoda su rincón, tu personaje encuentra una caja con semillas y una nota.','Sobre de semillas'],prepare:['Algo menos para mañana','Tu personaje organiza la mochila y encuentra espacio para llevar algo a un vecino.','Mochila preparada'],social:['Una conversación que sigue','Tu personaje saluda. La otra persona le cuenta que a veces se ven luces más allá del puente.','Postal de un encuentro'],hobby:['Algo hecho por gusto','Tu personaje crea un pequeño dibujo de la costa. Un vecino se detiene a mirarlo.','Dibujo de la costa'],food:['Una mesa con espacio','Tu personaje prepara algo sencillo. Deja una silla extra cerca de la mesa.','Receta de una tarde'],water:['Una pausa y un brote','Tu personaje hace una pausa. Al volver, observa un pequeño brote junto al escritorio.','Brote observado'],alcohol:['Un plan elegido por ti','Tu personaje piensa en su salida y prepara una alternativa para la mañana. La historia conserva espacio para lo que decida después.','Plan de una salida'],self:['Un lugar para lo que lograste','Tu personaje observa un dibujo, sonríe y decide dejarlo a la vista.','Recuerdo de un paso propio']};
function completeRun(run,commit,day,date,id){const a=ACTIONS[commit.action],v=CONSEQUENCES[commit.action];const record={id,action:commit.action,minutes:commit.duration,status:'done',day,date,choice:commit.situation};run.records.push(record);run.active=null;run.energy=Math.max(1,Math.min(5,run.energy+(['rest','sleep'].includes(commit.action)?1:a.physical?-1:0)));run.mood=a.anim;const changes=unlocks(run);const e={id:id+'e',day,date,kind:'reaction',title:v[0],text:v[1],action:commit.action,recordId:id};run.events.push(e);if(!run.memories.includes(v[2]))run.memories.push(v[2]);changes.forEach(u=>run.events.push({id:id+u.flag,day,date,kind:'unlock',title:u.title,text:u.text,recordId:id}));if(run.records.filter(r=>r.action===commit.action&&r.status==='done').length===1)run.future.push({id:id+'f',due:day+1,action:commit.action,recordId:id,title:'Lo que empezó con '+a.name.toLowerCase(),text:commit.action==='learn'||commit.action==='idea'?'La bibliotecaria dejó una nueva nota junto al símbolo. Puedes acercarte para decidir cómo seguir.':commit.action==='social'?'La persona que conociste vuelve a la plaza con una postal. Quiere mostrarte algo.':'El vecino vio el recuerdo que trajiste y dejó una pista en la plaza. Una pequeña acción sigue encontrando caminos.'});return{record,e,changes,animation:a.anim}}
